### PR TITLE
Add <editable-list/> web component example

### PR DESCRIPTION
**Pull request by mskalandunas**
After messing around with web components a bit, I wanted to throw an example out there.  It's a very basic todo list with add/remove buttons.

editable-list-example

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi there!

Thanks for contributing this — it is a cool little example.

A few small requests for further work:

1. The list items are a bit bunched together: maybe add some margin in between?
2. The buttons look a bit messy - the icon is not vertically centered
3. Could you add an entry to the project's README file for your example, in the same style as the others?
4. Could you think about making the example not use innerHTML to add the DOM structure? This is considered bad practice.

One more idea, although I don't expect you to act on it — since this is an extension to a list, did you consider making it a built-in element thanks extends list elements?

**Comment by mskalandunas** [comment]
Hey, will do! Thank you for getting back so quickly!

About the built-in– I considered it, but because I was adding siblings to the `ul` I decided on extending `HTMLElement` instead.  I'm actually not sure where to draw the line.

**Comment by chrisdavidmills** [comment]
That's fair enough. In this instance I don't think it makes all that much difference.

I just thought that it might make slightly more semantic sense to extend an existing list, with the initial items just written as <li>s and then grabbed and used in the shadow DOM, buttons added, etc., rather than defining them in attributes.

It would also be marginally better for backwards compatibility — if web components weren't supported it would just show up as a standard list.

But I'll not press you on this — it's just some suggestions basically.

**Comment by mskalandunas** [comment]
Hey @chrisdavidmills, I've updated the styles, added a readme, and remove the `innerHTML` happening post-append.

It's looking much cleaner after following your suggestions–

screen shot 2018-02-20 at 10 08 17 am

**Comment by chrisdavidmills** [comment]
Great - thanks! Your changes look good.

One more nitpick before I merge this — the buttons look pretty neat in Chrome, but in Firefox they look a bit scruffy, and in Safari they look terrible ;-)

Can you investigate why this is, and try to fix them up?

**Comment by mskalandunas** [comment]
Hahaha of course.  Will do.

**Comment by mskalandunas** [comment]
Fixed the button issue on both FF and Safari– looks like there were some default styles I wasn't accounting for.

I also decided to convert my attribute value gathering to using ES6 getter syntax.

**Comment by chrisdavidmills** [comment]
Looks cool! r+

merged.

**Comment by saggypatel** [comment]
I tried it in safari and looks like `is` attribute not supported, am I missing anything ?

@chrisdavidmills 

Screen Shot 2021-03-08 at 6 47 29 PM

**Comment by chrisdavidmills** [comment]
> I tried it in safari and looks like `is` attribute not supported, am I missing anything ?

Hi there! It's a while since I wrote this stuff, but it looks like Safari still doesn't support customized built-in elements; see the note at the top of https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by saggypatel** [comment]
> > I tried it in safari and looks like `is` attribute not supported, am I missing anything ?
> 
> Hi there! It's a while since I wrote this stuff, but it looks like Safari still doesn't support customized built-in elements; see the note at the top of https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

I see, thank you for the quick response.

**Pull request merged**
