### PR TITLE
Dialog modal example

### PR DESCRIPTION
**Pull request by jamigibbs**
Adding a simple dialog modal component. Attributes allow custom button and close text. Modal displays any provided HTML content:

modal-demo

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi @jamigibbs , this looks really nice, thanks for the contribution.

I had a couple of comments here about how this presented in the repo, and then a comment about its functionality in general.

First about the repo presentation:

1. Could you update the HTML file so that it is an actual HTML file with the script linked, so people can just click the gh-pages example and play with it? I appreciate that how you've presented it would be easier to include in a real project, but I'm more interested in learning applications and consistency with the rest of the repo.
2. Can you add an entry to the repo's readme file about this component, in the same manner as was done for the others?

Now about the functionality of the component. I was thinking, nice as the implementation is here, that it is difficult to actually style the button, because it is hidden inside the component. When you apply style to `dialog-modal { }`, it is only applied to the actual model content. I wonder whether it might be better to have this as a custom element that extends `<button>`, and then pass the template content in as a [template](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots), so that both are stylable?

**Comment by jamigibbs** [comment]
Thanks very much for your feedback @chrisdavidmills! It was a silly oversight on my part to forget to include those repo presentation points. I'll make sure to have the PR updated for them.

As for your functionality suggestion, I agree that styling is troublesome and honestly something that I was concerned about also but didn't quite know yet how to make it more flexible (this is an exercise for myself as I'm learning about web components).

Are you suggesting something like this where the button is pulled out into a template and we pass a custom version of it into the dialog modal component?

```
    <template id="dialog-modal-button">
        <style>
            .dialog-modal-button {
                padding: 10px 20px;
                background: white;
                border: 1px solid #ccc;
            }
        </style>
        <button class="dialog-modal-button">
            <slot name="dialog-modal-button__text">Default Text</slot>
        </button>
    </template>

    <dialog-modal closeButtonText="close">
        <dialog-modal-button>
            <span slot="dialog-modal-button__text">Open Modal Dialog</span>
        </dialog-modal-button>
        <div>
            <h1>Lorem ipsum dolar sit amet</h1>
            <p>Other modal dialog content...</p>
        </div>
    </dialog-modal>
```

**Comment by chrisdavidmills** [comment]
> Thanks very much for your feedback @chrisdavidmills! It was a silly oversight on my part to forget to include those repo presentation points. I'll make sure to have the PR updated for them.

No worries at all! I appreciate your time on this.

> Are you suggesting something like this where the button is pulled out into a template and we pass a custom version of it into the dialog modal component?

I was thinking of something more like this, where the content and styling for the modal is all handled in the template, and then the button is just a `<button>`, but extended with custom functionality.:

```
<template id="dialog-modal">
        <style>
            .dialog-modal {
                padding: 10px 20px;
                background: white;
                border: 1px solid #ccc;
            }
        </style>
        <div class="dialog-modal">
            <h1>Lorem ipsum dolar sit amet</h1>
            <p>Other modal dialog content...</p>
        </div>
</template>

    <button is="dialog-modal-button" data-close-label="Close!">Open Modal Dialog</button>
```

You could pull the template content and data close label into the shadow DOM using JS like what you see at https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots#Using_templates_with_web_components

And the element register line would look more like this:

```
customElements.define('dialog-modal-button', DialogModalButton, { extends: "button" });
```

At least, I think this is how it would go. Have a play and let me know how you get on.

**Comment by jamigibbs** [comment]
Sorry for the delay @chrisdavidmills. Life got in the way.

I've made an update here but really it's a complete rewrite. In this version, styling is far more flexible based on your suggestion. I've split out the component into a custom button and custom dialog template (as you suggested) and a custom event ties them both together. The class now only contains the bare minimum style to make the modal function but otherwise, all styling can now be customized either in the template (for the modal content) or a separate stylesheet (for the button).

**Comment by chrisdavidmills** [comment]
Hi Jami,

This is certainly getting there, nice work! The template usage is pretty cool, and pretty much what I was expecting.

I had a few follow-on comments:

1. I see you've done this as two separate custom elements. I'd probably just do this as a single custom element, with a single `<template>` element to feed the DOM structure. Any DOM manipulation can all be done inside the Shadow DOM. Ideally, you'd only need to write something like the following in the actual content markup:

```<button is="dialog-modal-button" data-close-label="Close!">Open Modal Dialog</button>```

As it is, it is still a bit messy to include this.

2. The styling for the `<button>` should go inside the document head (or an external stylesheet), not inside the `<div>` you've included the custom elements in.

3. The modal dialog button and the close button should both be given a styling of `cursor: pointer;` (or similar) so that is more obvious they are interactable.

4. You should represent the close button using an actual button element, or at least make it focusable using tabindex, etc. At the moment it is impossible to close the dialog with the keyboard

**Comment by abrahamcuenca** [comment]
What is the status of this PR?

**Comment by chrisdavidmills** [comment]
My feedback was never answered, so I'm going to close this one for now.

**Pull request closed without merging**
