### PR TITLE
Update example of web component

### PR DESCRIPTION
**Pull request by gullerya**
The documentation along with the best practices says to move some of the constructing logic to the `connectedCallback` - this PR adjusts the example accordingly.

### CODE REVIEW

**Review by ralyodio — APPROVED** [review]

**Comment by bsmth** [comment]
Closing this as a duplicate of https://github.com/mdn/web-components-examples/pull/54

**Comment by bsmth** [comment]
Sorry I was too quick to close, there are some other changes to review here :)

**Comment by sideshowbarker** [comment]
This seems preferable to what #54 does — and probably should be merged instead (and #54 should be closed).

But @gullerya if we do this, the corresponding code in the https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements article itself should also be updated. Would you be willing to open PR for doing that?

**Comment by wbamberg** [comment]
This is superseded by https://github.com/mdn/web-components-examples/pull/62.

**Comment by bsmth** [comment]
Looks like this is resolved in the linked PR, so I am closing now. Thank you :)

- [x] https://github.com/mdn/web-components-examples/pull/62

**Pull request closed without merging**
